import type { LazyExoticComponent, ComponentType } from "react";
import { lazy } from "react";
type ButtonComponent = LazyExoticComponent<
    ComponentType<{ paused?: boolean }>
    >;

export const buttonAnimationMap: Record<string, ButtonComponent> = {
    floating: lazy(() => import("./examples/basic/FloatingButton")),
    bulbul: lazy(() => import("./examples/basic/BulbulButton")),
    thump: lazy(() => import("./examples/basic/ThumpButton")),
    swaying: lazy(() => import("./examples/basic/SwayingButton")),
    shaky: lazy(() => import("./examples/basic/ShakyButton")),
    sparkling: lazy(() => import("./examples/basic/SparklingButton")),
    ripples: lazy(() => import("./examples/basic/RipplesButton")),
    skew: lazy(() => import("./examples/basic/SkewButton")),
    spin: lazy(() => import("./examples/basic/SpinButton")),
    jiggly: lazy(() => import("./examples/basic/JigglyButton")),
    clickMove: lazy(() => import("./examples/basic/ClickMoveButton")),
    gradientMove: lazy(() => import("./examples/basic/GradientMoveButton")),

    changeText: lazy(() => import("./examples/hover-text/ChangeTextButton")),
    flowText: lazy(() => import("./examples/hover-text/FlowTextButton")),
    fancyText: lazy(() => import("./examples/hover-text/FancyTextButton")),
    smokeText: lazy(() => import("./examples/hover-text/SmokeTextButton")),
    bouncyText: lazy(() => import("./examples/hover-text/BouncyTextButton")),

    extendLeft: lazy(() => import("./examples/hover/ExtendLeftButton")),
    diagonalSwipe: lazy(() => import("./examples/hover/DiagonalSwipeButton")),
    doubleSwipe: lazy(() => import("./examples/hover/DoubleSwipeButton")),
    stopSwipe: lazy(() => import("./examples/hover/StopSwipeButton")),
    passing: lazy(() => import("./examples/hover/PassingButton")),
    circleOut: lazy(() => import("./examples/hover/CircleOutButton")),
    click: lazy(() => import("./examples/hover/ClickButton")),
    flip: lazy(() => import("./examples/hover/FlipButton")),
    colorCycle: lazy(() => import("./examples/hover/ColorCycleButton")),
    colorIntoCenter: lazy(() => import("./examples/hover/ColorIntoCenterButton")),
    changeShape: lazy(() => import("./examples/hover/ChangeShapeButton")),
    hiddenText: lazy(() => import("./examples/hover/HiddenTextButton")),
    colorFlow: lazy(() => import("./examples/hover/ColorFlowButton")),
    mochi: lazy(() => import("./examples/hover/MochiButton")),
    wave: lazy(() => import("./examples/hover/WaveButton")),
    backgroundMoves: lazy(() => import("./examples/hover/BackgroundMovesButton")),
    gradientSlide: lazy(() => import("./examples/hover/GradientSlideButton")),
    pixelHover: lazy(() => import("./examples/hover/PixelHoverButton")),
    bubble: lazy(() => import("./examples/hover/BubbleButton")),
    letterFill: lazy(() => import("./examples/hover/LetterFillButton")),
    everChanging: lazy(() => import("./examples/hover/EverChangingButton")),
    liquid: lazy(() => import("./examples/hover/LiquidButton")),
    gradient3D: lazy(() => import("./examples/hover/Gradient3DButton")),

    sideBrackets: lazy(() => import("./examples/hover-line/SideBracketsButton")),
    transformShape: lazy(() => import("./examples/hover-line/TransformShapeButton")),
    hoverLine: lazy(() => import("./examples/hover-line/HoverLineButton")),
    rotate: lazy(() => import("./examples/hover-line/RotateButton")),
    arrowExtend: lazy(() => import("./examples/hover-line/ArrowExtendButton")),
    sporty: lazy(() => import("./examples/hover-line/SportyButton")),
    hoverOutline: lazy(() => import("./examples/hover-line/HoverOutlineButton")),
    hover4Corner: lazy(() => import("./examples/hover-line/Hover4CornerButton")),
    hoverSurround: lazy(() => import("./examples/hover-line/HoverSurroundButton")),
    pileUp: lazy(() => import("./examples/hover-line/PileUpButton")),
    parallelogram: lazy(() => import("./examples/hover-line/ParallelogramButton")),
    parallelogram2: lazy(() => import("./examples/hover-line/Parallelogram2Button")),
    outlineHover: lazy(() => import("./examples/hover-line/OutlineHoverButton")),
    moveAndSurround: lazy(() => import("./examples/hover-line/MoveAndSurroundButton")),
    lineSurround: lazy(() => import("./examples/hover-line/LineSurroundButton")),
};